// 1. Find the total number of active categories.
[
    {
        '$match': {
            'is_Active': true
        }
    }, {
        '$count': 'string'
    }
]

// 2. Retrieve the list of users who have made more than 3 orders.
[
    {
        '$group': {
            '_id': '$user_id',
            'userOrder': {
                '$sum': 1
            }
        }
    },
    {
        '$match': {
            'userOrder': { '$gt': 3 }
        }
    }
]

// 3. Calculate the total revenue generated by each seller.
[
    {
        '$group': {
            '_id': '$seller_id',
            'TotalRevenue': {
                '$sum': '$total_amount'
            }
        }
    }
]

// 4. Retrieve the products with the highest average rating.
[
    {
        '$lookup': {
            'from': 'product',
            'localField': 'product_id',
            'foreignField': '_id',
            'as': 'product'
        }
    }, {
        '$project': {
            'product_id': '$product_id',
            'product': '$product',
            'rating': '$rating'
        }
    }, {
        '$group': {
            '_id': '$product_id',
            'avgRatings': {
                '$avg': '$rating'
            }
        }
    }, {
        '$sort': {
            'avgRatings': -1
        }
    }, {
        '$limit': 1
    }
]

// 5. Calculate the total number of products in each subcategory.


